import { StyleSheet } from 'react-native';
import { df } from '@/constants/typography';

export const articleStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#0C0D0F',
  },
  content: {
    paddingBottom: 28,
  },
  /** Full-width strip matching design: black bar + tab icons + utilities */
  articleHeaderStrip: {
    backgroundColor: '#000000',
    borderBottomWidth: 1,
    borderBottomColor: '#27292D',
  },
  articleBrandShrink: {
    flexShrink: 0,
  },
  navCluster: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
    minWidth: 0,
    paddingHorizontal: 4,
  },
  navIconHit: {
    padding: 6,
  },
  articleActionsShrink: {
    flexShrink: 0,
  },
  backToolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#27292D',
    backgroundColor: '#131417',
  },
  backRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  backText: {
    fontSize: df(11),
    lineHeight: df(16),
    color: '#9498A2',
    textTransform: 'uppercase',
    letterSpacing: 0.2,
    fontFamily: 'JetBrainsMono',
  },
  heroTextBlock: {
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 14,
    gap: 10,
    backgroundColor: '#0C0D0F',
  },
  metaTop: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 10,
  },
  sourceBadge: {
    backgroundColor: '#EE343B',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  sourceBadgeText: {
    fontSize: df(10),
    lineHeight: df(15),
    color: '#FCFCFC',
    textTransform: 'uppercase',
    letterSpacing: 0.45,
    fontFamily: 'InterBold',
  },
  metaTime: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  metaTimeText: {
    fontSize: df(10),
    lineHeight: df(15),
    color: '#9498A2',
    textTransform: 'uppercase',
    letterSpacing: 0.2,
    fontFamily: 'JetBrainsMono',
  },
  heroTitle: {
    fontSize: df(26),
    lineHeight: df(30),
    color: '#F0F2F5',
    fontFamily: 'GeorgiaBold',
    letterSpacing: -0.35,
  },
  heroSubhead: {
    fontSize: df(16),
    lineHeight: df(22),
    color: '#9498A2',
    fontFamily: 'InterRegular',
  },
  publishedRow: {
    paddingTop: 2,
  },
  publishedText: {
    fontSize: df(10),
    lineHeight: df(15),
    color: '#9498A2',
    letterSpacing: 0.2,
    fontFamily: 'JetBrainsMono',
    textTransform: 'uppercase',
  },
  heroImage: {
    width: '100%',
    height: 220,
    backgroundColor: '#1E1F23',
  },
  body: {
    padding: 12,
    gap: 8,
  },
  meta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  metaText: {
    fontSize: df(10),
    lineHeight: df(15),
    color: '#9498A2',
    textTransform: 'uppercase',
    letterSpacing: 0.2,
    fontFamily: 'JetBrainsMono',
  },
  sourceText: {
    color: '#EE343B',
  },
  title: {
    fontSize: df(40),
    lineHeight: df(42),
    color: '#F0F2F5',
    fontFamily: 'GeorgiaBold',
    letterSpacing: -0.5,
  },
  description: {
    marginTop: 2,
    fontSize: df(28),
    lineHeight: df(34),
    color: '#9498A2',
    fontFamily: 'GeorgiaRegular',
    letterSpacing: -0.3,
  },
  aiBriefCard: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#27292D',
    backgroundColor: '#121212',
    overflow: 'hidden',
  },
  aiBriefHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#101113',
  },
  aiBriefHeaderExpanded: {
    borderBottomWidth: 1,
    borderBottomColor: '#27292D',
  },
  aiBriefHeaderLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  aiBriefTitle: {
    fontSize: df(10),
    lineHeight: df(15),
    color: '#F0F2F5',
    textTransform: 'uppercase',
    letterSpacing: 0.35,
    fontFamily: 'InterBold',
  },
  aiBriefHeaderCenter: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  aiBriefDot: {
    fontSize: df(10),
    color: '#757575',
    fontFamily: 'JetBrainsMono',
  },
  aiBriefSub: {
    fontSize: df(10),
    lineHeight: df(15),
    color: '#757575',
    textTransform: 'uppercase',
    letterSpacing: 0.25,
    fontFamily: 'JetBrainsMono',
  },
  aiBriefHeaderRight: {
    flex: 1,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  aiBriefBody: {
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 10,
    gap: 10,
  },
  aiBriefTldrLabel: {
    fontSize: df(10),
    lineHeight: df(15),
    color: '#FF4D4D',
    textTransform: 'uppercase',
    letterSpacing: 0.35,
    fontFamily: 'InterBold',
  },
  aiBriefSummary: {
    fontSize: df(14),
    lineHeight: df(21),
    color: '#E0E0E0',
    fontFamily: 'InterRegular',
  },
  aiBriefBullets: {
    gap: 8,
    paddingLeft: 2,
  },
  aiBriefBulletRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  aiBriefBulletSquare: {
    width: 5,
    height: 5,
    marginTop: 6,
    backgroundColor: '#FF4D4D',
  },
  aiBriefBulletText: {
    flex: 1,
    fontSize: df(13),
    lineHeight: df(19),
    color: '#E0E0E0',
    fontFamily: 'InterRegular',
  },
  aiBriefDivider: {
    height: 1,
    backgroundColor: '#27292D',
    marginVertical: 4,
  },
  aiBriefWhyLabel: {
    fontSize: df(10),
    lineHeight: df(15),
    color: '#E8C547',
    textTransform: 'uppercase',
    letterSpacing: 0.35,
    fontFamily: 'InterBold',
  },
  aiBriefWhyBody: {
    fontSize: df(13),
    lineHeight: df(20),
    color: '#BDBDBD',
    fontFamily: 'InterRegular',
  },
  aiBriefFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingTop: 4,
    paddingBottom: 8,
  },
  aiBriefFooterLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  aiBriefReadTime: {
    fontSize: df(11),
    lineHeight: df(16),
    color: '#757575',
    fontFamily: 'JetBrainsMono',
  },
  aiBriefRegenerate: {
    fontSize: df(10),
    lineHeight: df(15),
    color: '#FF4D4D',
    textTransform: 'uppercase',
    letterSpacing: 0.35,
    fontFamily: 'InterBold',
  },
  aiBriefDisclaimer: {
    paddingHorizontal: 12,
    paddingBottom: 12,
    fontSize: df(9),
    lineHeight: df(13),
    color: '#5C5C5C',
    fontFamily: 'InterRegular',
  },
  actions: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 10,
  },
  actionBtn: {
    flex: 1,
    minHeight: 34,
    borderWidth: 1,
    borderColor: '#27292D',
    backgroundColor: '#131417',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 6,
    flexDirection: 'row',
    gap: 4,
  },
  primaryBtn: {
    backgroundColor: '#EE343B',
    borderColor: '#EE343B',
    flex: 1.2,
  },
  actionText: {
    fontSize: df(10),
    lineHeight: df(15),
    color: '#F0F2F5',
    textTransform: 'uppercase',
    letterSpacing: 0.2,
    fontFamily: 'JetBrainsMono',
  },
  primaryText: {
    color: '#FCFCFC',
  },
  disabled: {
    opacity: 0.45,
  },
  sourceLink: {
    marginTop: 10,
    fontSize: df(10),
    lineHeight: df(15),
    color: '#9498A2',
    textTransform: 'uppercase',
    letterSpacing: 0.2,
    fontFamily: 'JetBrainsMono',
  },
  articleBody: {
    marginTop: 12,
    fontSize: df(12),
    lineHeight: df(18),
    letterSpacing: -0.2,
    color: '#D7DBE3',
    fontFamily: 'InterRegular',
  },
  askAiCard: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#27292D',
    backgroundColor: '#131417',
    overflow: 'hidden',
  },
  askAiHeader: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#27292D',
    backgroundColor: '#101113',
  },
  askAiHeaderTitle: {
    flex: 1,
    flexShrink: 1,
    minWidth: 120,
    fontSize: df(10),
    lineHeight: df(15),
    color: '#F0F2F5',
    textTransform: 'uppercase',
    letterSpacing: 0.25,
    fontFamily: 'JetBrainsMono',
  },
  askAiBeta: {
    fontSize: df(10),
    lineHeight: df(15),
    color: '#E8C547',
    textTransform: 'uppercase',
    letterSpacing: 0.25,
    fontFamily: 'JetBrainsMono',
  },
  askAiInner: {
    padding: 12,
    gap: 10,
  },
  askAiPrompt: {
    fontSize: df(12),
    lineHeight: df(18),
    color: '#9498A2',
    fontFamily: 'InterRegular',
  },
  askAiChipGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  askAiChip: {
    borderWidth: 1,
    borderColor: '#D7DBE3',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#0C0D0F',
  },
  askAiChipPressed: {
    opacity: 0.75,
  },
  askAiChipText: {
    fontSize: df(12),
    lineHeight: df(17),
    color: '#F0F2F5',
    fontFamily: 'InterRegular',
  },
  askAiSignInBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 2,
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#5C5F66',
    backgroundColor: '#101113',
  },
  askAiSignInPressed: {
    opacity: 0.85,
  },
  askAiSignInText: {
    fontSize: df(11),
    lineHeight: df(16),
    color: '#F0F2F5',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
    fontFamily: 'JetBrainsMono',
  },
  askAiWarningRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    marginTop: 2,
  },
  askAiWarningText: {
    flex: 1,
    fontSize: df(10),
    lineHeight: df(15),
    color: '#757575',
    fontFamily: 'InterRegular',
  },
  evidenceCard: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#27292D',
    backgroundColor: '#131417',
    overflow: 'hidden',
  },
  evidenceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#27292D',
    backgroundColor: '#101113',
  },
  evidenceHeaderText: {
    flex: 1,
    fontSize: df(10),
    lineHeight: df(15),
    color: '#F0F2F5',
    textTransform: 'uppercase',
    letterSpacing: 0.25,
    fontFamily: 'JetBrainsMono',
  },
  evidenceBody: {
    padding: 12,
    gap: 12,
    alignItems: 'center',
  },
  evidenceSignInBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    alignSelf: 'stretch',
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#5C5F66',
    backgroundColor: '#101113',
  },
  evidenceSignInPressed: {
    opacity: 0.85,
  },
  evidenceSignInText: {
    fontSize: df(11),
    lineHeight: df(16),
    color: '#F0F2F5',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
    fontFamily: 'JetBrainsMono',
  },
  evidencePlaceholder: {
    fontSize: df(12),
    lineHeight: df(18),
    color: '#9498A2',
    fontFamily: 'InterRegular',
    textAlign: 'center',
  },
  communityCard: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#27292D',
    backgroundColor: '#131417',
    overflow: 'hidden',
  },
  communityHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#27292D',
    backgroundColor: '#101113',
  },
  communityHeaderLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    minWidth: 0,
  },
  communityTitleCluster: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'baseline',
    gap: 8,
  },
  communityTitleMain: {
    fontSize: df(10),
    lineHeight: df(15),
    color: '#F0F2F5',
    textTransform: 'uppercase',
    letterSpacing: 0.25,
    fontFamily: 'JetBrainsMono',
  },
  communityTitleCount: {
    fontSize: df(9),
    lineHeight: df(14),
    color: '#9498A2',
    textTransform: 'uppercase',
    letterSpacing: 0.2,
    fontFamily: 'JetBrainsMono',
  },
  communityStatusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: '#4ADE80',
    backgroundColor: '#0C0D0F',
    flexShrink: 0,
    maxWidth: '48%',
  },
  communityStatusBadgeText: {
    flex: 1,
    fontSize: df(8),
    lineHeight: df(12),
    color: '#4ADE80',
    textTransform: 'uppercase',
    letterSpacing: 0.15,
    fontFamily: 'JetBrainsMono',
  },
  communityBody: {
    padding: 12,
    gap: 0,
    alignItems: 'stretch',
  },
  communityAggregateBlock: {
    marginBottom: 14,
    gap: 8,
  },
  communityAggregateBar: {
    flexDirection: 'row',
    height: 12,
    borderRadius: 4,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#27292D',
  },
  communityAggregateGreen: {
    backgroundColor: '#22C55E',
  },
  communityAggregateRed: {
    backgroundColor: '#EF4444',
  },
  communitySentimentLabels: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sentimentReal: {
    fontSize: df(10),
    lineHeight: df(15),
    color: '#4ADE80',
    textTransform: 'uppercase',
    letterSpacing: 0.2,
    fontFamily: 'JetBrainsMono',
  },
  sentimentFake: {
    fontSize: df(10),
    lineHeight: df(15),
    color: '#FF4D4D',
    textTransform: 'uppercase',
    letterSpacing: 0.2,
    fontFamily: 'JetBrainsMono',
  },
  communityComposer: {
    gap: 10,
    marginBottom: 16,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#27292D',
  },
  communityInput: {
    borderWidth: 1,
    borderColor: '#27292D',
    backgroundColor: '#0C0D0F',
    paddingHorizontal: 10,
    paddingVertical: 10,
    fontSize: df(13),
    lineHeight: df(18),
    color: '#F0F2F5',
    fontFamily: 'InterRegular',
  },
  communityTextArea: {
    borderWidth: 1,
    borderColor: '#27292D',
    backgroundColor: '#0C0D0F',
    paddingHorizontal: 10,
    paddingVertical: 10,
    minHeight: 88,
    fontSize: df(13),
    lineHeight: df(19),
    color: '#F0F2F5',
    fontFamily: 'InterRegular',
  },
  communityCheckboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  communityCheckboxBox: {
    width: 18,
    height: 18,
    borderWidth: 1,
    borderColor: '#5C5F66',
    backgroundColor: '#0C0D0F',
    justifyContent: 'center',
    alignItems: 'center',
  },
  communityCheckboxBoxOn: {
    backgroundColor: '#EE343B',
    borderColor: '#EE343B',
  },
  communityCheckboxLabel: {
    flex: 1,
    fontSize: df(12),
    lineHeight: df(17),
    color: '#D7DBE3',
    fontFamily: 'InterRegular',
  },
  communityPostRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  communityPostBtn: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: '#9F1520',
    borderWidth: 1,
    borderColor: '#EE343B',
  },
  communityPostBtnPressed: {
    opacity: 0.88,
  },
  communityPostBtnText: {
    fontSize: df(10),
    lineHeight: df(15),
    color: '#FCFCFC',
    textTransform: 'uppercase',
    letterSpacing: 0.25,
    fontFamily: 'JetBrainsMono',
  },
  communityMockDisclaimer: {
    fontSize: df(9),
    lineHeight: df(13),
    color: '#5C5C5C',
    fontFamily: 'InterRegular',
  },
  communityComment: {
    paddingTop: 12,
    paddingBottom: 4,
  },
  communityCommentDivider: {
    borderTopWidth: 1,
    borderTopColor: '#27292D',
    marginTop: 4,
  },
  communityCommentMeta: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
  },
  communityCommentMetaLeft: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 8,
  },
  communityUsername: {
    fontSize: df(14),
    lineHeight: df(20),
    color: '#F0F2F5',
    fontFamily: 'InterBold',
  },
  communityVerifiedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderWidth: 1,
    borderColor: '#E8C547',
  },
  communityVerifiedText: {
    fontSize: df(9),
    lineHeight: df(13),
    color: '#E8C547',
    textTransform: 'uppercase',
    letterSpacing: 0.2,
    fontFamily: 'JetBrainsMono',
  },
  communityTimestamp: {
    fontSize: df(11),
    lineHeight: df(16),
    color: '#9498A2',
    fontFamily: 'InterRegular',
  },
  communityCredential: {
    marginTop: 4,
    fontSize: df(10),
    lineHeight: df(15),
    color: '#9498A2',
    textTransform: 'uppercase',
    letterSpacing: 0.15,
    fontFamily: 'JetBrainsMono',
  },
  communityCommentBody: {
    marginTop: 8,
    fontSize: df(13),
    lineHeight: df(20),
    color: '#F0F2F5',
    fontFamily: 'InterRegular',
  },
  communityVoteRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 12,
    flexWrap: 'wrap',
  },
  communityVoteBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: '#27292D',
    backgroundColor: '#101113',
  },
  communityVoteBtnPressed: {
    opacity: 0.75,
  },
  communityVoteBtnText: {
    fontSize: df(10),
    lineHeight: df(14),
    color: '#4ADE80',
    textTransform: 'uppercase',
    letterSpacing: 0.15,
    fontFamily: 'JetBrainsMono',
  },
  communityVoteBtnTextFake: {
    color: '#FF4D4D',
  },
  communityMiniBarWrap: {
    flex: 1,
    minWidth: 72,
    minHeight: 28,
    justifyContent: 'center',
  },
  communityMiniBar: {
    flexDirection: 'row',
    height: 5,
    borderRadius: 2,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#27292D',
  },
  communityMiniGreen: {
    backgroundColor: '#22C55E',
  },
  communityMiniRed: {
    backgroundColor: '#EF4444',
  },
});
