import { StyleSheet } from 'react-native';

import { PAGE_MAX_WIDTH } from '@/constants/layout';
import { df } from '@/constants/typography';

export const authStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#0C0D0F',
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
    justifyContent: 'center',
  },
  card: {
    backgroundColor: '#131417',
    padding: 24,
    gap: 12,
  },
  heading: {
    fontSize: df(42),
    color: '#F0F2F5',
    fontFamily: 'GeorgiaBold',
  },
  title: {
    fontSize: df(24),
    lineHeight: df(26),
    color: '#F0F2F5',
    fontFamily: 'GeorgiaBold',
  },
  body: {
    fontSize: df(12),
    lineHeight: df(16),
    color: '#9498A2',
    fontFamily: 'InterRegular',
  },
  divider: {
    borderBottomWidth: 1,
    borderBottomColor: '#27292D',
    paddingBottom: 12,
    marginBottom: 8,
  },
  form: {
    gap: 24,
    paddingBottom: 2,
  },
  input: {
    height: 34,
    backgroundColor: '#0C0D0F',
    color: '#F0F2F5',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#EE343B',
    fontSize: df(12),
    lineHeight: df(15),
    fontFamily: 'InterRegular',
  },
  primaryButton: {
    height: 27,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#EE343B',
  },
  primaryButtonText: {
    color: '#FCFCFC',
    fontSize: df(10),
    letterSpacing: 0.2,
    textTransform: 'uppercase',
    fontFamily: 'JetBrainsMono',
  },
  link: {
    color: '#F0F2F5',
    fontFamily: 'InterBold',
  },
  helper: {
    fontSize: df(12),
    lineHeight: df(16),
    color: '#9498A2',
    fontFamily: 'InterRegular',
  },
  forgotPasswordRow: {
    alignSelf: 'stretch',
    alignItems: 'flex-end',
    marginTop: -2,
    marginBottom: 6,
  },
  forgotPasswordText: {
    fontSize: df(12),
    lineHeight: df(16),
    color: '#9498A2',
    fontFamily: 'InterRegular',
    textAlign: 'right',
  },
  forgotPasswordTextHighlight: {
    color: '#F0F2F5',
    fontFamily: 'InterBold',
  },
  signUpRow: {
    alignItems: 'center',
    marginTop: 8,
  },
  signUpText: {
    fontSize: df(12),
    lineHeight: df(16),
    color: '#9498A2',
    fontFamily: 'InterRegular',
  },
  signUpTextHighlight: {
    color: '#F0F2F5',
    fontFamily: 'InterBold',
  },
  helperLinksRow: {
    flexDirection: 'row',
    gap: 12,
    flexWrap: 'wrap',
  },
  rememberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  rememberBox: {
    width: 12,
    height: 12,
    borderWidth: 1,
    borderColor: '#9498A2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rememberBoxChecked: {
    borderColor: '#EE343B',
    backgroundColor: 'rgba(238, 52, 59, 0.25)',
  },
  rememberText: {
    fontSize: df(12),
    lineHeight: df(15),
    color: '#F0F2F5',
    fontFamily: 'InterRegular',
  },
  header: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#27292D',
    backgroundColor: 'rgba(12, 13, 15, 0.95)',
    justifyContent: 'center',
  },
  headerInner: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerMax: {
    width: '100%',
    maxWidth: PAGE_MAX_WIDTH,
    alignSelf: 'center',
  },
  headerRowDesktop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    width: '100%',
  },
  headerRowCompact: {
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 10,
    width: '100%',
  },
  headerNavCenter: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    minWidth: 0,
    paddingHorizontal: 8,
  },
  headerNavScrollInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 4,
  },
  headerActionsEnd: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flexShrink: 0,
  },
  /** Mobile app header: actions can wrap on very narrow phones. */
  headerActionsEndMobile: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
    flexShrink: 0,
    flexWrap: 'wrap',
    rowGap: 6,
  },
  mobileHeaderBrand: {
    flex: 1,
    minWidth: 0,
  },
  mobileHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    gap: 12,
  },
  headerActionsCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
    flexWrap: 'wrap',
  },
  navTab: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  navTabActive: {
    borderBottomColor: '#EE343B',
  },
  navTabLabel: {
    color: '#9498A2',
    fontSize: df(11),
    letterSpacing: 0.55,
    textTransform: 'uppercase',
    fontFamily: 'JetBrainsMono',
  },
  navTabLabelActive: {
    color: '#FCFCFC',
  },
  outlineHeaderButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#27292D',
  },
  outlineHeaderButtonText: {
    color: '#F0F2F5',
    fontSize: df(10),
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    fontFamily: 'JetBrainsMono',
  },
  liveClockRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  liveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#EE343B',
  },
  liveLabel: {
    color: '#9498A2',
    fontSize: df(10),
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    fontFamily: 'JetBrainsMono',
  },
  clockText: {
    color: '#9498A2',
    fontSize: df(11),
    fontFamily: 'JetBrainsMono',
    fontVariant: ['tabular-nums'],
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  logoBox: {
    width: 28,
    height: 28,
    backgroundColor: '#EE343B',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoImage: {
    width: 28,
    height: 28,
    resizeMode: 'contain',
  },
  logoN: {
    color: '#FCFCFC',
    fontSize: df(15),
    lineHeight: df(17),
    fontFamily: 'GeorgiaBold',
    textAlign: 'center',
    includeFontPadding: false,
  },
  brandTextWrap: {
    justifyContent: 'center',
  },
  brandTitle: {
    color: '#F0F2F5',
    fontSize: df(14),
    lineHeight: df(20),
    letterSpacing: -0.35,
    fontFamily: 'GeorgiaBold',
  },
  brandSub: {
    color: '#9498A2',
    fontSize: df(8),
    lineHeight: df(10),
    textTransform: 'uppercase',
    letterSpacing: 0.16,
    fontFamily: 'JetBrainsMono',
  },
  headerActions: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  iconButton: {
    width: 22,
    height: 22,
    borderWidth: 1,
    borderColor: '#27292D',
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerWrap: {
    backgroundColor: '#131417',
    paddingTop: 48,
    paddingHorizontal: 24,
    paddingBottom: 16,
  },
  footerInner: {
    borderTopWidth: 1,
    borderTopColor: '#27292D',
    paddingVertical: 24,
    alignItems: 'center',
    gap: 20,
  },
  footerTop: {
    width: '100%',
    maxWidth: 342,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  footerCopy: {
    color: '#9498A2',
    fontSize: df(12),
    textTransform: 'uppercase',
    letterSpacing: 0.24,
    fontFamily: 'JetBrainsMono',
  },
  interestButton: {
    backgroundColor: 'rgba(238, 52, 59, 0.1)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  interestButtonText: {
    color: '#F0F2F5',
    fontSize: df(12),
    textTransform: 'uppercase',
    letterSpacing: 0.24,
    fontFamily: 'JetBrainsMono',
  },
  poweredBy: {
    color: '#9498A2',
    fontSize: df(12),
    textTransform: 'uppercase',
    letterSpacing: 0.24,
    fontFamily: 'JetBrainsMono',
  },
});
