import { StyleSheet } from 'react-native';

export const eventsStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#0C0D0F',
  },
  scroll: {
    paddingTop: 0,
  },
  scrollContent: {
    paddingBottom: 40,
  },
  content: {
    paddingHorizontal: 8,
    paddingVertical: 12,
    gap: 12,
  },
  introRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  introText: {
    fontSize: 10,
    lineHeight: 15,
    letterSpacing: 0.2,
    textTransform: 'uppercase',
    fontFamily: 'JetBrainsMono',
    color: '#EE343B',
  },
  title: {
    fontSize: 24,
    lineHeight: 26,
    letterSpacing: -0.36,
    color: '#F0F2F5',
    fontFamily: 'GeorgiaBold',
  },
  subtitle: {
    fontSize: 20,
    lineHeight: 22,
    letterSpacing: -0.24,
    color: '#F0F2F5',
    fontFamily: 'GeorgiaBold',
  },
  body: {
    fontSize: 12,
    lineHeight: 16,
    color: '#9498A2',
    fontFamily: 'InterRegular',
  },
  divider: {
    borderBottomWidth: 1,
    borderBottomColor: '#27292D',
    marginTop: 6,
  },
  locationButton: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: '#27292D',
    backgroundColor: '#131417',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  locationButtonText: {
    fontSize: 10,
    lineHeight: 15,
    letterSpacing: 0.2,
    textTransform: 'uppercase',
    color: '#F0F2F5',
    fontFamily: 'JetBrainsMono',
  },
  chipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  chip: {
    borderWidth: 1,
    borderColor: '#27292D',
    backgroundColor: '#131417',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  chipActive: {
    borderColor: '#EE343B',
    backgroundColor: 'rgba(238, 52, 59, 0.15)',
  },
  chipText: {
    fontSize: 10,
    lineHeight: 15,
    letterSpacing: 0.2,
    textTransform: 'uppercase',
    color: '#9498A2',
    fontFamily: 'JetBrainsMono',
  },
  chipTextActive: {
    color: '#F0F2F5',
  },
  cityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  cityInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#27292D',
    backgroundColor: '#0C0D0F',
    color: '#F0F2F5',
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'InterRegular',
  },
  cityPicker: {
    minWidth: 124,
    borderWidth: 1,
    borderColor: '#27292D',
    backgroundColor: '#131417',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  cityPickerText: {
    fontSize: 16,
    lineHeight: 20,
    color: '#F0F2F5',
    fontFamily: 'GeorgiaBold',
  },
  goButton: {
    borderWidth: 1,
    borderColor: '#EE343B',
    backgroundColor: '#6f1b20',
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  goButtonText: {
    fontSize: 12,
    lineHeight: 16,
    textTransform: 'uppercase',
    color: '#EE343B',
    fontFamily: 'JetBrainsMono',
  },
  sectionLabel: {
    fontSize: 10,
    lineHeight: 15,
    letterSpacing: 0.3,
    textTransform: 'uppercase',
    color: '#9498A2',
    fontFamily: 'JetBrainsMono',
  },
  dateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  dateField: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#27292D',
    backgroundColor: '#0C0D0F',
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dateFieldLabel: {
    fontSize: 12,
    lineHeight: 16,
    color: '#F0F2F5',
    fontFamily: 'JetBrainsMono',
  },
  pickerHeader: {
    marginTop: 8,
    alignItems: 'flex-end',
  },
  pickerDoneButton: {
    borderWidth: 1,
    borderColor: '#27292D',
    backgroundColor: '#131417',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  pickerDoneText: {
    fontSize: 10,
    lineHeight: 15,
    textTransform: 'uppercase',
    color: '#F0F2F5',
    fontFamily: 'JetBrainsMono',
  },
  sortRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  sortButton: {
    borderWidth: 1,
    borderColor: '#27292D',
    backgroundColor: '#131417',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  sortLabel: {
    fontSize: 12,
    lineHeight: 14,
    textTransform: 'uppercase',
    color: '#9498A2',
    fontFamily: 'JetBrainsMono',
  },
  sortValue: {
    fontSize: 16,
    lineHeight: 20,
    color: '#F0F2F5',
    fontFamily: 'GeorgiaBold',
  },
  filtersCard: {
    borderWidth: 1,
    borderColor: '#27292D',
    backgroundColor: '#131417',
    padding: 12,
    gap: 12,
  },
  filtersHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  filtersTitle: {
    fontSize: 12,
    lineHeight: 16,
    color: '#9498A2',
    fontFamily: 'JetBrainsMono',
    textTransform: 'uppercase',
  },
  emptyState: {
    borderWidth: 1,
    borderColor: '#27292D',
    backgroundColor: '#131417',
    minHeight: 240,
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  emptyTitle: {
    fontSize: 24,
    lineHeight: 28,
    color: '#F0F2F5',
    fontFamily: 'GeorgiaBold',
    textAlign: 'center',
  },
  emptyText: {
    fontSize: 12,
    lineHeight: 16,
    color: '#9498A2',
    fontFamily: 'InterRegular',
    textAlign: 'center',
  },
  tryAgainButton: {
    borderWidth: 1,
    borderColor: '#27292D',
    backgroundColor: '#0C0D0F',
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  tryAgainText: {
    fontSize: 14,
    lineHeight: 16,
    textTransform: 'uppercase',
    color: '#F0F2F5',
    fontFamily: 'JetBrainsMono',
  },
  footnote: {
    fontSize: 12,
    lineHeight: 18,
    color: '#9498A2',
    fontFamily: 'InterRegular',
  },
});
