import { StyleSheet } from 'react-native';

export const feedsStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#0C0D0F',
  },
  content: {
    paddingTop: 0,
  },
  scrollContent: {
    paddingBottom: 50,
  },
  categoriesBar: {
    backgroundColor: 'rgba(19, 20, 23, 0.5)',
    borderBottomWidth: 1,
    borderBottomColor: '#27292D',
    paddingHorizontal: 4,
  },
  categoriesContent: {
    paddingVertical: 4,
    paddingRight: 16,
  },
  categoryButton: {
    paddingHorizontal: 8,
    paddingVertical: 8,
    marginRight: 2,
  },
  categoryLabel: {
    fontSize: 10,
    lineHeight: 15,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    fontFamily: 'InterRegular',
    color: '#9498A2',
  },
  categoryLabelActive: {
    color: '#F0F2F5',
    fontFamily: 'InterBold',
  },
  categoryUnderline: {
    marginTop: 6,
    height: 2,
    backgroundColor: '#EE343B',
  },
  feedContainer: {
    paddingHorizontal: 8,
    paddingVertical: 16,
    gap: 16,
    overflow: 'hidden',
  },
  titleRow: {
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#27292D',
  },
  sectionText: {
    fontSize: 10,
    lineHeight: 15,
    letterSpacing: 0.2,
    textTransform: 'uppercase',
    fontFamily: 'JetBrainsMono',
    color: '#EE343B',
  },
  headingText: {
    marginTop: 4,
    fontSize: 24,
    lineHeight: 26,
    letterSpacing: -0.36,
    fontFamily: 'GeorgiaBold',
    color: '#F0F2F5',
  },
  featuredCard: {
    borderWidth: 1,
    borderColor: '#27292D',
    backgroundColor: '#131417',
    overflow: 'hidden',
  },
  featuredImage: {
    height: 232,
    width: '100%',
  },
  imageOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'space-between',
    padding: 12,
    backgroundColor: 'rgba(12, 13, 15, 0.35)',
  },
  badgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  badgePrimary: {
    backgroundColor: '#EE343B',
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  badgeSecondary: {
    backgroundColor: 'rgba(12, 13, 15, 0.8)',
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  badgeTextPrimary: {
    fontSize: 10,
    lineHeight: 15,
    textTransform: 'uppercase',
    fontFamily: 'JetBrainsMono',
    color: '#FCFCFC',
  },
  badgeTextSecondary: {
    fontSize: 10,
    lineHeight: 15,
    textTransform: 'uppercase',
    fontFamily: 'JetBrainsMono',
    color: '#F0F2F5',
  },
  saveButton: {
    position: 'absolute',
    top: 12,
    right: 12,
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(12, 13, 15, 0.8)',
  },
  featuredContent: {
    gap: 6,
  },
  featuredTitle: {
    fontSize: 24,
    lineHeight: 26,
    letterSpacing: -0.24,
    fontFamily: 'GeorgiaBold',
    color: '#F0F2F5',
  },
  featuredDescription: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'InterRegular',
    color: '#9498A2',
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexShrink: 1,
    minWidth: 0,
  },
  metaText: {
    fontSize: 10,
    lineHeight: 15,
    letterSpacing: 0.2,
    textTransform: 'uppercase',
    fontFamily: 'JetBrainsMono',
    color: '#9498A2',
    flexShrink: 1,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 14,
  },
  gridCard: {
    width: '48%',
    borderWidth: 1,
    borderColor: '#27292D',
    backgroundColor: '#131417',
  },
  fullWidthCard: {
    width: '100%',
  },
  gridImageWrap: {
    position: 'relative',
  },
  gridImage: {
    width: '100%',
    height: 100,
    backgroundColor: '#1E1F23',
  },
  fullWidthImage: {
    height: 160,
  },
  gridSaveButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(12, 13, 15, 0.8)',
  },
  gridContent: {
    padding: 12,
    gap: 6,
  },
  sourceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minWidth: 0,
  },
  sourceText: {
    fontSize: 9,
    lineHeight: 14,
    letterSpacing: 0.18,
    textTransform: 'uppercase',
    fontFamily: 'JetBrainsMono',
    color: '#EE343B',
    flexShrink: 0,
    flexGrow: 1,
  },
  dotText: {
    fontSize: 9,
    lineHeight: 14,
    color: '#9498A2',
    fontFamily: 'JetBrainsMono',
    flexShrink: 0,
  },
  agoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 4,
  },
  gridTitle: {
    fontSize: 16,
    lineHeight: 18,
    letterSpacing: -0.24,
    color: '#F0F2F5',
    fontFamily: 'GeorgiaBold',
  },
  gridDescription: {
    fontSize: 12,
    lineHeight: 16,
    color: '#9498A2',
    fontFamily: 'InterRegular',
  },
  emptyStateCard: {
    borderWidth: 1,
    borderColor: '#27292D',
    backgroundColor: '#131417',
    padding: 20,
    alignItems: 'center',
    gap: 10,
  },
  emptyStateIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1E1F23',
  },
  emptyStateTitle: {
    fontSize: 16,
    lineHeight: 20,
    color: '#F0F2F5',
    fontFamily: 'GeorgiaBold',
  },
  emptyStateDescription: {
    fontSize: 12,
    lineHeight: 16,
    color: '#9498A2',
    fontFamily: 'InterRegular',
    textAlign: 'center',
  },
});
