import { FEED_GRID_GAP } from '@/constants/layout';
import { df } from '@/constants/typography';
import { Platform, StyleSheet } from 'react-native';

export const feedsStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#0C0D0F',
  },
  content: {
    paddingTop: 0,
  },
  scrollContent: {
    paddingBottom: 50,
  },
  categoriesBar: {
    backgroundColor: 'rgba(19, 20, 23, 0.5)',
    borderBottomWidth: 1,
    borderBottomColor: '#27292D',
    paddingHorizontal: 4,
  },
  categoriesContent: {
    paddingVertical: 4,
    paddingRight: 16,
  },
  categoryButton: {
    paddingHorizontal: 8,
    paddingVertical: 8,
    marginRight: 2,
  },
  categoryLabel: {
    fontSize: df(12),
    lineHeight: df(18),
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    fontFamily: 'InterRegular',
    color: '#9498A2',
  },
  categoryLabelActive: {
    color: '#F0F2F5',
    fontFamily: 'InterBold',
  },
  categoryUnderline: {
    marginTop: 6,
    height: 2,
    backgroundColor: '#EE343B',
  },
  feedContainer: {
    paddingHorizontal: 8,
    paddingVertical: 16,
    gap: 16,
    overflow: 'hidden',
  },
  titleRow: {
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#27292D',
  },
  sectionText: {
    fontSize: df(12),
    lineHeight: df(18),
    letterSpacing: 0.2,
    textTransform: 'uppercase',
    fontFamily: 'JetBrainsMono',
    color: '#EE343B',
  },
  headingText: {
    marginTop: 4,
    fontSize: df(28),
    lineHeight: df(34),
    letterSpacing: -0.36,
    fontFamily: 'GeorgiaBold',
    color: '#F0F2F5',
  },
  featuredCard: {
    borderWidth: 1,
    borderColor: '#27292D',
    backgroundColor: '#131417',
    overflow: 'hidden',
    marginBottom: 12,
  },
  featuredCardHover: {
    borderColor: '#EE343B',
  },
  featuredImageClip: {
    width: '100%',
    overflow: 'hidden',
    ...(Platform.OS === 'web' || Platform.OS === 'macos'
      ? { aspectRatio: 16 / 10 }
      : { height: 232 }),
  },
  featuredImageZoomHost: {
    width: '100%',
    height: '100%',
  },
  featuredImageFill: {
    width: '100%',
    height: '100%',
    backgroundColor: '#1E1F23',
  },
  featuredTitleHover: {
    color: '#EE343B',
  },
  imageOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'space-between',
    padding: 12,
    backgroundColor: 'rgba(12, 13, 15, 0.35)',
  },
  badgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  badgePrimary: {
    backgroundColor: '#EE343B',
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  badgeSecondary: {
    backgroundColor: 'rgba(12, 13, 15, 0.8)',
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  badgeTextPrimary: {
    fontSize: df(12),
    lineHeight: df(18),
    textTransform: 'uppercase',
    fontFamily: 'JetBrainsMono',
    color: '#FCFCFC',
  },
  badgeTextSecondary: {
    fontSize: df(12),
    lineHeight: df(18),
    textTransform: 'uppercase',
    fontFamily: 'JetBrainsMono',
    color: '#F0F2F5',
  },
  saveButton: {
    position: 'absolute',
    top: 12,
    right: 12,
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(12, 13, 15, 0.8)',
  },
  featuredContent: {
    gap: 6,
  },
  featuredTitle: {
    fontSize: df(28),
    lineHeight: df(34),
    letterSpacing: -0.24,
    fontFamily: 'GeorgiaBold',
    color: '#F0F2F5',
  },
  featuredDescription: {
    fontSize: df(14),
    lineHeight: df(20),
    fontFamily: 'InterRegular',
    color: '#9498A2',
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexShrink: 1,
    minWidth: 0,
  },
  metaText: {
    fontSize: df(12),
    lineHeight: df(18),
    letterSpacing: 0.2,
    textTransform: 'uppercase',
    fontFamily: 'JetBrainsMono',
    color: '#9498A2',
    flexShrink: 1,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    alignContent: 'flex-start',
    gap: FEED_GRID_GAP,
  },
  gridCard: {
    borderWidth: 1,
    borderColor: '#27292D',
    backgroundColor: '#131417',
    overflow: 'hidden',
  },
  gridCardHover: {
    borderColor: '#EE343B',
  },
  fullWidthCard: {
    width: '100%',
  },
  gridImageWrap: {
    position: 'relative',
    overflow: 'hidden',
    height: 100,
  },
  gridImageWrapFull: {
    height: 160,
  },
  gridImageZoomHost: {
    width: '100%',
    height: '100%',
  },
  gridImage: {
    width: '100%',
    height: '100%',
    backgroundColor: '#1E1F23',
  },
  gridTitleHover: {
    color: '#EE343B',
  },
  gridSaveButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(12, 13, 15, 0.8)',
  },
  gridContent: {
    padding: 12,
    gap: 6,
  },
  sourceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minWidth: 0,
  },
  sourceText: {
    fontSize: df(11),
    lineHeight: df(17),
    letterSpacing: 0.18,
    textTransform: 'uppercase',
    fontFamily: 'JetBrainsMono',
    color: '#EE343B',
    flexShrink: 0,
    flexGrow: 1,
  },
  dotText: {
    fontSize: df(11),
    lineHeight: df(17),
    color: '#9498A2',
    fontFamily: 'JetBrainsMono',
    flexShrink: 0,
  },
  agoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 4,
  },
  gridTitle: {
    fontSize: df(18),
    lineHeight: df(22),
    letterSpacing: -0.24,
    color: '#F0F2F5',
    fontFamily: 'GeorgiaBold',
  },
  gridDescription: {
    fontSize: df(14),
    lineHeight: df(20),
    color: '#9498A2',
    fontFamily: 'InterRegular',
  },
  emptyStateCard: {
    borderWidth: 1,
    borderColor: '#27292D',
    backgroundColor: '#131417',
    padding: 20,
    alignItems: 'center',
    gap: 10,
  },
  emptyStateIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1E1F23',
  },
  emptyStateTitle: {
    fontSize: df(18),
    lineHeight: df(24),
    color: '#F0F2F5',
    fontFamily: 'GeorgiaBold',
  },
  emptyStateDescription: {
    fontSize: df(14),
    lineHeight: df(20),
    color: '#9498A2',
    fontFamily: 'InterRegular',
    textAlign: 'center',
  },
});
