import { StyleSheet } from 'react-native';
import { df } from '@/constants/typography';

export const personalizeStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.55)',
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  sheet: {
    maxHeight: '92%',
    backgroundColor: '#131417',
    borderWidth: 1,
    borderColor: '#27292D',
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 16,
  },
  headerBar: {
    backgroundColor: '#1B1D21',
    padding: 16,
    gap: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#27292D',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  headerLabel: {
    fontSize: df(10),
    lineHeight: df(15),
    letterSpacing: 0.2,
    textTransform: 'uppercase',
    fontFamily: 'JetBrainsMono',
    color: '#EE343B',
  },
  title: {
    fontSize: df(20),
    lineHeight: df(22),
    letterSpacing: -0.3,
    fontFamily: 'GeorgiaBold',
    color: '#F0F2F5',
  },
  subtitle: {
    fontSize: df(12),
    lineHeight: df(16),
    fontFamily: 'InterRegular',
    color: '#9498A2',
  },
  closeBtn: {
    position: 'absolute',
    top: 14,
    right: 14,
    padding: 8,
    opacity: 0.85,
  },
  scroll: {
    flexGrow: 0,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 24,
    gap: 20,
  },
  section: {
    gap: 8,
  },
  sectionHeadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  sectionHeading: {
    fontSize: df(10),
    lineHeight: df(15),
    letterSpacing: 0.2,
    textTransform: 'uppercase',
    fontFamily: 'JetBrainsMono',
    color: '#9498A2',
  },
  chipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  chipCat: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#27292D',
    backgroundColor: 'transparent',
  },
  chipCatSelected: {
    borderColor: '#EE343B',
    backgroundColor: 'rgba(238, 52, 59, 0.08)',
  },
  chipCatText: {
    fontSize: df(11),
    lineHeight: df(16),
    letterSpacing: 0.55,
    textTransform: 'uppercase',
    fontFamily: 'InterRegular',
    color: '#9498A2',
  },
  chipCatTextSelected: {
    color: '#F0F2F5',
  },
  chipTopic: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#27292D',
  },
  chipTopicSelected: {
    borderColor: '#EE343B',
    backgroundColor: 'rgba(238, 52, 59, 0.08)',
  },
  chipTopicText: {
    fontSize: df(11),
    lineHeight: df(16),
    fontFamily: 'InterRegular',
    color: '#9498A2',
  },
  chipTopicTextSelected: {
    color: '#F0F2F5',
  },
  addRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 4,
  },
  addInput: {
    flex: 1,
    height: 36,
    paddingHorizontal: 12,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#27292D',
    backgroundColor: '#0C0D0F',
    fontSize: df(14),
    fontFamily: 'InterRegular',
    color: '#F0F2F5',
  },
  addBtn: {
    width: 42,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#27292D',
    backgroundColor: '#0C0D0F',
  },
  geoRow: {
    gap: 8,
  },
  geoSelect: {
    height: 36,
    paddingHorizontal: 12,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#27292D',
    backgroundColor: '#0C0D0F',
    justifyContent: 'center',
  },
  geoSelectText: {
    fontSize: df(14),
    fontFamily: 'InterRegular',
    color: '#F0F2F5',
  },
  cityInput: {
    height: 36,
    paddingHorizontal: 12,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#27292D',
    backgroundColor: '#0C0D0F',
    fontSize: df(14),
    fontFamily: 'InterRegular',
    color: '#F0F2F5',
  },
  countryMenu: {
    borderWidth: 1,
    borderColor: '#27292D',
    borderRadius: 4,
    maxHeight: 160,
    backgroundColor: '#0C0D0F',
  },
  countryMenuItem: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#27292D',
  },
  countryMenuItemText: {
    fontSize: df(14),
    color: '#F0F2F5',
    fontFamily: 'InterRegular',
  },
  previewMuted: {
    color: '#9498A2',
    fontSize: df(12),
    fontFamily: 'InterRegular',
  },
  previewBody: {
    flex: 1,
  },
  previewCard: {
    borderWidth: 1,
    borderColor: '#27292D',
    backgroundColor: 'rgba(12, 13, 15, 0.4)',
    borderRadius: 4,
    overflow: 'hidden',
  },
  previewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#1B1D21',
    borderBottomWidth: 1,
    borderBottomColor: '#27292D',
  },
  previewHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  previewHeaderTitle: {
    fontSize: df(10),
    lineHeight: df(15),
    letterSpacing: 0.2,
    textTransform: 'uppercase',
    fontFamily: 'JetBrainsMono',
    color: '#F0F2F5',
  },
  previewHeaderMeta: {
    fontSize: df(10),
    fontFamily: 'JetBrainsMono',
    color: '#9498A2',
    textTransform: 'uppercase',
    letterSpacing: 0.2,
  },
  previewHintRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#27292D',
  },
  previewHintAccent: {
    fontSize: df(10),
    fontFamily: 'JetBrainsMono',
    color: '#EE343B',
    textTransform: 'uppercase',
    letterSpacing: 0.2,
  },
  previewHint: {
    flex: 1,
    fontSize: df(10),
    lineHeight: df(15),
    fontFamily: 'InterRegular',
    color: 'rgba(148, 152, 162, 0.85)',
  },
  previewList: {
    padding: 8,
    gap: 8,
    minHeight: 80,
  },
  previewRow: {
    flexDirection: 'row',
    gap: 8,
    padding: 8,
    backgroundColor: '#131417',
    borderWidth: 1,
    borderColor: 'rgba(39, 41, 45, 0.6)',
    borderRadius: 4,
  },
  previewThumb: {
    width: 64,
    height: 48,
    borderRadius: 4,
    backgroundColor: '#1E1F23',
  },
  previewTitle: {
    flex: 1,
    fontSize: df(12),
    lineHeight: df(16),
    fontFamily: 'InterBold',
    color: '#F0F2F5',
  },
  previewMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 4,
  },
  previewSource: {
    fontSize: df(10),
    lineHeight: df(15),
    fontFamily: 'InterRegular',
    color: '#9498A2',
  },
  footerBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#1B1D21',
    borderTopWidth: 1,
    borderTopColor: '#27292D',
    gap: 12,
  },
  skipText: {
    fontSize: df(11),
    lineHeight: df(16),
    letterSpacing: 0.22,
    textTransform: 'uppercase',
    fontFamily: 'JetBrainsMono',
    color: '#9498A2',
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  saveBtn: {
    flex: 1,
    maxWidth: 200,
    paddingVertical: 10,
    paddingHorizontal: 16,
    backgroundColor: '#EE343B',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
  },
  saveBtnText: {
    fontSize: df(11),
    lineHeight: df(16),
    letterSpacing: 0.22,
    textTransform: 'uppercase',
    fontFamily: 'JetBrainsMono',
    color: '#FCFCFC',
  },
});
