/** Preset chips for “Hobbies, work & topics” (matches design). */
export const PERSONALIZE_TOPIC_TAGS: string[] = [
  'AI',
  'Startups',
  'Crypto',
  'Climate',
  'Space',
  'Football',
  'Formula 1',
  'Basketball',
  'Cycling',
  'Hiking',
  'Photography',
  'Gaming',
  'Movies',
  'Music',
  'Cooking',
  'Travel',
  'Fashion',
  'Stock Market',
  'Real Estate',
  'Productivity',
  'Design',
  'Programming',
  'Cybersecurity',
  'Healthcare',
  'Education',
  'Politics',
  'Books',
  'EVs',
];
